/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {


    public static void main(String[] args){

        try {
            Scanner scanner =new Scanner(System.in);
            Gson gson =new Gson();

            Reader reader = Files.newBufferedReader(Paths.get("C:\\Users\\ghl1590\\java\\quotes\\resources\\book.json"));
            System.out.println("done");
            BookContact[] bookContact = gson.fromJson(reader,BookContact[].class); //https://howtodoinjava.com/gson/gson-parse-json-array/

            System.out.println("Please enter the author name");
            String author = scanner.nextLine();
            System.out.println(searchByAuthor(bookContact,author));

            System.out.println("");

            System.out.println("Please enter one word for the quote");
            String word = scanner.nextLine();
            System.out.println(searchByWord(bookContact,word));


        }catch (IOException exception){
            System.err.println(exception.getMessage());
        }



     }

     public static String searchByAuthor(BookContact[] bookContacts, String author){

         for (BookContact val:bookContacts
              ) {
             if(val.author.equals(author)){
                return val.text;
             }
         }
         return "not found";
     }

     public static String searchByWord(BookContact[] bookContacts, String word){
         for (BookContact val:bookContacts
         ) {
             if(val.text.contains(word)){
                return val.text;

             }
         }
         return "not found";
     }
}
